# -*- coding: utf-8 -*-
"""TextSummarizer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yYzgNZE5KAT585aoXKI2V9iPagd5hqno
"""

#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


from traitlets.config.loader import load_pyconfig_files
import streamlit as st
from langchain import OpenAI
from langchain.docstore.document import Document
from langchain.text_splitter import CharacterTextSplitter
from langchain.chains.summarize import load_summarize_chain

def generate_response(text):
  llm = OpenAI(temperature= 0, openai_api_key= api_key)
  text_splitter = CharacterTextSplitter()
  texts = text_splitter.split_text(text)
  docs = [Document(page_content=t) for t in texts]
  chain = load_summarize_chain(llm, chain_type='map_reduce')
  return chain.run(docs)

# Page title
st.set_page_config(page_title=" Text Summarization App")
st.title("Hajra's firstText Summarization App")

# Text input
txt_input = st.text_area('Enter your text', '', height=200)

# Form to accept user's text input for summarization
result = []
with st.form('summarize_form', clear_on_submit=True):
    openai_api_key = st.text_input('OpenAI API Key', type = 'password', disabled=not txt_input)
    submitted = st.form_submit_button('Submit')
    if submitted and openai_api_key.startswith('sk-'):
        with st.spinner('Calculating...'):
            response = generate_response(txt_input)
            result.append(response)
            del openai_api_key

if len(result):
    st.info(response)

